#!/usr/bin/env python3

import netrc
import sys

import mechanicalsoup
from urllib.parse import urlparse

PLAYER_URL = 'https://system.81dojo.com/en/players/show/'
HOST = urlparse(PLAYER_URL).hostname
KIFUS_URL = 'https://system.81dojo.com/api/v2/kifus'

netrc = netrc.netrc()
info = netrc.authenticators(HOST)
if info is None:
    sys.exit('~/.netrc should include: machine #{HOST} login [...] '
             'password [...]')

user, password = info[0], info[2]

browser = mechanicalsoup.StatefulBrowser()
browser.open(PLAYER_URL + user)
page = browser.get_current_page()
game_stats = page.find(text='Games').find_next('td').contents[0]
print(game_stats)
